RawTables = ['external_raw_data_28car', 'external_raw_data_anson', 'external_raw_data_asiaxpat',
             'external_raw_data_audi', 'external_raw_data_bettermotors', 'external_raw_data_beyondcar',
             'external_raw_data_bmw', 'external_raw_data_buycarhk', 'external_raw_data_car2soso',
             'external_raw_data_car8', 'external_raw_data_carboss', 'external_raw_data_carcity',
             'external_raw_data_carone', 'external_raw_data_carousell', 'external_raw_data_carsexit',
             'external_raw_data_cazbuyer', 'external_raw_data_dch', 'external_raw_data_deluxe',
             'external_raw_data_driverdotcom', 'external_raw_data_fb', 'external_raw_data_ferrari',
             'external_raw_data_gainfull', 'external_raw_data_glorious', 'external_raw_data_goldencentury',
             'external_raw_data_hkcartrader', 'external_raw_data_hyundai', 'external_raw_data_iautomobile',
             'external_raw_data_inchcape', 'external_raw_data_jaguar', 'external_raw_data_klm',
             'external_raw_data_landrover', 'external_raw_data_mazda', 'external_raw_data_mclaren',
             'external_raw_data_mycarhk', 'external_raw_data_newway', 'external_raw_data_porsche',
             'external_raw_data_pricedotcom', 'external_raw_data_starlite', 'external_raw_data_sunling',
             'external_raw_data_tesla', 'external_raw_data_usedcarhk', 'external_raw_data_usedcarmart',
             'external_raw_data_vincent', 'external_raw_data_vins', 'external_raw_data_volkswagen',
             'external_raw_data_zhonghwa', 'external_raw_data_zungfu']

ListTables = ['external_raw_data_28car_list', 'external_raw_data_28cardealer_list', 'external_raw_data_anson_list',
              'external_raw_data_asiaxpat_list', 'external_raw_data_audi_list', 'external_raw_data_bettermotors_list',
              'external_raw_data_beyondcar_list', 'external_raw_data_bmw_list', 'external_raw_data_buycarhk_list',
              'external_raw_data_car2soso_list', 'external_raw_data_car8_list', 'external_raw_data_carboss_list',
              'external_raw_data_carcity_list', 'external_raw_data_carone_list', 'external_raw_data_carousell_list',
              'external_raw_data_carsexit_list', 'external_raw_data_cazbuyer_list', 'external_raw_data_dch_list',
              'external_raw_data_deluxe_list', 'external_raw_data_driverdotcom_list', 'external_raw_data_fb_list',
              'external_raw_data_fb_list2', 'external_raw_data_fb_list_img', 'external_raw_data_ferrari_list',
              'external_raw_data_gainfull_list', 'external_raw_data_glorious_list',
              'external_raw_data_goldencentury_list', 'external_raw_data_hkcartrader_list',
              'external_raw_data_hyundai_list', 'external_raw_data_iautomobile_list',
              'external_raw_data_iautomobile_list_img', 'external_raw_data_inchcape_list',
              'external_raw_data_jaguar_list', 'external_raw_data_klm_list', 'external_raw_data_landrover_list',
              'external_raw_data_mazda_list', 'external_raw_data_mclaren_list', 'external_raw_data_mycarhk_list',
              'external_raw_data_newway_list', 'external_raw_data_porsche_list', 'external_raw_data_pricedotcom_list',
              'external_raw_data_starlite_list', 'external_raw_data_sunling_list', 'external_raw_data_tesla_list',
              'external_raw_data_usedcarhk_list', 'external_raw_data_usedcarmart_list',
              'external_raw_data_vincent_list', 'external_raw_data_vins_list', 'external_raw_data_volkswagen_list',
              'external_raw_data_zhonghwa_list', 'external_raw_data_zungfu_list']

